# name: Build And Test on EC2

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     container: swift:6.0-noble

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4
#     - name: Build
#       working-directory: ./backend
#       run: swift build

#   test:
#     runs-on: ubuntu-latest
#     container: swift:6.0-noble
    
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4
#     - name: Run tests
#       working-directory: ./backend
#       run: swift test