name: Build And Test on EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:6.0.3-amazonlinux2

    steps:
      - name: Manually Clone repository
        run: |
          # Clone the repository
          git clone https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          cd ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        working-directory: ${{ github.event.repository.name }}/backend
        run: swift build

  # test:
  #   runs-on: ubuntu-latest
  #   container: swift:6.0.3-amazonlinux2
    
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Run tests
  #     working-directory: ./backend
  #     run: swift test