name: Build And Test on EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:6.0.3-amazonlinux2

    steps:
      # GitHub checkout action has a dep on NodeJS 20 which is not running on Amazonlinux2
      # workaround is to manually checkout the repository
      # https://github.com/actions/checkout/issues/1487
      - name: Manually Clone repository
        run: |
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" .
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Build
        working-directory: backend
        run: swift build

  test:
    runs-on: ubuntu-latest
    container: swift:6.0.3-amazonlinux2
    
    steps:
      # GitHub checkout action has a dep on NodeJS 20 which is not running on Amazonlinux2
      # workaround is to manually checkout the repository
      # https://github.com/actions/checkout/issues/1487
    - name: Manually Clone repository
      run: |
        git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" .
        git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Run tests
      working-directory: ./backend
      run: swift test